### ISSUE TITLE
Can't unzip files in /mask

### ISSUE THREAD

**Issue by veronica320** [FerreroJeremy/Cross-Language-Dataset#1]
Hello,

Could you please check if the .zip files under the /mask directory are corrupt ? Once I attempt to unzip it, a .cpgz file is created. And once I unzip the .cpgz file, another .zip file is created...It's an endless loop.

Thanks for your help!!

**Comment by FerreroJeremy** [comment]
Hello,
first, thank you for your concern about this project.
Secondly, I took another look at archives and all is fine.

Are you on OSX or other UNIX-based OS, or on Windows?
If you are on UNIX-based OS, like OSX, update your unarchiver (or use gzip or unzip command).
If you are on Windows, use a zip compatible unarchiver, like 7-zip on WinRAR.

**Comment by veronica320** [comment]
Thanks for your reply! It turns out that the problem was when downloading the whole repo, the mask files weren't downloaded completely (I tried several times and it was always the case). Downloading the files individually works for me.
